version: '3.8'
services:
  postgres:
    platform: linux/x86_64
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: i18n
      POSTGRES_USER: i18n
      POSTGRES_PASSWORD: i18n
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq